// Generated by tools/visual-tests/generate-visual-tests.js -- do not edit by hand.
// Readiness/stubbing logic lives in tools/visual-tests/spec-helpers.js.
import { test } from '@playwright/test';
import runBlockVisualTest from '../../spec-helpers.js';

const BLOCK_SLUG = 'detailed-teaser';

test.describe('detailed-teaser Visual Tests', () => {
  test('detailed-teaser (light, left, cta1-primary, cta2-primary) visual test at Mobile viewport', async ({ page }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/detailed-teaser&index=0&vtest=true',
      viewport: { width: 320, height: 568 },
      screenshotName: 'detailed-teaser-0-Mobile.png',
    });
  });

  test('detailed-teaser (light, left, cta1-primary, cta2-primary) visual test at Tablet viewport', async ({ page }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/detailed-teaser&index=0&vtest=true',
      viewport: { width: 768, height: 1024 },
      screenshotName: 'detailed-teaser-0-Tablet.png',
    });
  });

  test('detailed-teaser (light, left, cta1-primary, cta2-primary) visual test at Desktop viewport', async ({
    page,
  }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/detailed-teaser&index=0&vtest=true',
      viewport: { width: 1024, height: 768 },
      screenshotName: 'detailed-teaser-0-Desktop.png',
    });
  });

  test('detailed-teaser (light, left, cta1-primary, cta2-primary) visual test at Large viewport', async ({ page }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/detailed-teaser&index=0&vtest=true',
      viewport: { width: 1440, height: 900 },
      screenshotName: 'detailed-teaser-0-Large.png',
    });
  });

  test('detailed-teaser (cta1-primary, cta2-primary, dark, right, bg-spectrum-gray-900) visual test at Mobile viewport', async ({
    page,
  }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/detailed-teaser&index=1&vtest=true',
      viewport: { width: 320, height: 568 },
      screenshotName: 'detailed-teaser-1-Mobile.png',
    });
  });

  test('detailed-teaser (cta1-primary, cta2-primary, dark, right, bg-spectrum-gray-900) visual test at Tablet viewport', async ({
    page,
  }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/detailed-teaser&index=1&vtest=true',
      viewport: { width: 768, height: 1024 },
      screenshotName: 'detailed-teaser-1-Tablet.png',
    });
  });

  test('detailed-teaser (cta1-primary, cta2-primary, dark, right, bg-spectrum-gray-900) visual test at Desktop viewport', async ({
    page,
  }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/detailed-teaser&index=1&vtest=true',
      viewport: { width: 1024, height: 768 },
      screenshotName: 'detailed-teaser-1-Desktop.png',
    });
  });

  test('detailed-teaser (cta1-primary, cta2-primary, dark, right, bg-spectrum-gray-900) visual test at Large viewport', async ({
    page,
  }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/detailed-teaser&index=1&vtest=true',
      viewport: { width: 1440, height: 900 },
      screenshotName: 'detailed-teaser-1-Large.png',
    });
  });

  test('detailed-teaser (left, cta2-primary, light, cta1-custom, cta1-bg-spectrum-celery-700, cta1-text-black, bg-spectrum-yellow-700, fifty-split-layout) visual test at Mobile viewport', async ({
    page,
  }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/detailed-teaser&index=2&vtest=true',
      viewport: { width: 320, height: 568 },
      screenshotName: 'detailed-teaser-2-Mobile.png',
    });
  });

  test('detailed-teaser (left, cta2-primary, light, cta1-custom, cta1-bg-spectrum-celery-700, cta1-text-black, bg-spectrum-yellow-700, fifty-split-layout) visual test at Tablet viewport', async ({
    page,
  }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/detailed-teaser&index=2&vtest=true',
      viewport: { width: 768, height: 1024 },
      screenshotName: 'detailed-teaser-2-Tablet.png',
    });
  });

  test('detailed-teaser (left, cta2-primary, light, cta1-custom, cta1-bg-spectrum-celery-700, cta1-text-black, bg-spectrum-yellow-700, fifty-split-layout) visual test at Desktop viewport', async ({
    page,
  }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/detailed-teaser&index=2&vtest=true',
      viewport: { width: 1024, height: 768 },
      screenshotName: 'detailed-teaser-2-Desktop.png',
    });
  });

  test('detailed-teaser (left, cta2-primary, light, cta1-custom, cta1-bg-spectrum-celery-700, cta1-text-black, bg-spectrum-yellow-700, fifty-split-layout) visual test at Large viewport', async ({
    page,
  }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/detailed-teaser&index=2&vtest=true',
      viewport: { width: 1440, height: 900 },
      screenshotName: 'detailed-teaser-2-Large.png',
    });
  });
});
