// Generated by tools/visual-tests/generate-visual-tests.js -- do not edit by hand.
// Readiness/stubbing logic lives in tools/visual-tests/spec-helpers.js.
import { test } from '@playwright/test';
import runBlockVisualTest from '../../spec-helpers.js';

const BLOCK_SLUG = 'browse-filters';

test.describe('browse-filters Visual Tests', () => {
  test('browse-filters visual test at Mobile viewport', async ({ page }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/browse-filters&index=0&vtest=true',
      viewport: { width: 320, height: 568 },
      screenshotName: 'browse-filters-0-Mobile.png',
    });
  });

  test('browse-filters visual test at Tablet viewport', async ({ page }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/browse-filters&index=0&vtest=true',
      viewport: { width: 768, height: 1024 },
      screenshotName: 'browse-filters-0-Tablet.png',
    });
  });

  test('browse-filters visual test at Desktop viewport', async ({ page }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/browse-filters&index=0&vtest=true',
      viewport: { width: 1024, height: 768 },
      screenshotName: 'browse-filters-0-Desktop.png',
    });
  });

  test('browse-filters visual test at Large viewport', async ({ page }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/browse-filters&index=0&vtest=true',
      viewport: { width: 1440, height: 900 },
      screenshotName: 'browse-filters-0-Large.png',
    });
  });
});
