// Generated by tools/visual-tests/generate-visual-tests.js -- do not edit by hand.
// Readiness/stubbing logic lives in tools/visual-tests/spec-helpers.js.
import { test } from '@playwright/test';
import runBlockVisualTest from '../../spec-helpers.js';

const BLOCK_SLUG = 'code';

test.describe('code Visual Tests', () => {
  test('code (language-javascript) visual test at Mobile viewport', async ({ page }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/code&index=0&vtest=true',
      viewport: { width: 320, height: 568 },
      screenshotName: 'code-0-Mobile.png',
    });
  });

  test('code (language-javascript) visual test at Tablet viewport', async ({ page }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/code&index=0&vtest=true',
      viewport: { width: 768, height: 1024 },
      screenshotName: 'code-0-Tablet.png',
    });
  });

  test('code (language-javascript) visual test at Desktop viewport', async ({ page }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/code&index=0&vtest=true',
      viewport: { width: 1024, height: 768 },
      screenshotName: 'code-0-Desktop.png',
    });
  });

  test('code (language-javascript) visual test at Large viewport', async ({ page }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/code&index=0&vtest=true',
      viewport: { width: 1440, height: 900 },
      screenshotName: 'code-0-Large.png',
    });
  });
});
