// Generated by tools/visual-tests/generate-visual-tests.js -- do not edit by hand.
// Readiness/stubbing logic lives in tools/visual-tests/spec-helpers.js.
import { test } from '@playwright/test';
import runBlockVisualTest from '../../spec-helpers.js';

const BLOCK_SLUG = 'curated-cards';

test.describe('curated-cards Visual Tests', () => {
  test('curated-cards (header-left) (0) visual test at Mobile viewport', async ({ page }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/curated-cards&index=0&vtest=true',
      viewport: { width: 320, height: 568 },
      screenshotName: 'curated-cards-0-Mobile.png',
    });
  });

  test('curated-cards (header-left) (0) visual test at Tablet viewport', async ({ page }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/curated-cards&index=0&vtest=true',
      viewport: { width: 768, height: 1024 },
      screenshotName: 'curated-cards-0-Tablet.png',
    });
  });

  test('curated-cards (header-left) (0) visual test at Desktop viewport', async ({ page }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/curated-cards&index=0&vtest=true',
      viewport: { width: 1024, height: 768 },
      screenshotName: 'curated-cards-0-Desktop.png',
    });
  });

  test('curated-cards (header-left) (0) visual test at Large viewport', async ({ page }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/curated-cards&index=0&vtest=true',
      viewport: { width: 1440, height: 900 },
      screenshotName: 'curated-cards-0-Large.png',
    });
  });

  test('curated-cards (header-left) (1) visual test at Mobile viewport', async ({ page }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/curated-cards&index=1&vtest=true',
      viewport: { width: 320, height: 568 },
      screenshotName: 'curated-cards-1-Mobile.png',
    });
  });

  test('curated-cards (header-left) (1) visual test at Tablet viewport', async ({ page }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/curated-cards&index=1&vtest=true',
      viewport: { width: 768, height: 1024 },
      screenshotName: 'curated-cards-1-Tablet.png',
    });
  });

  test('curated-cards (header-left) (1) visual test at Desktop viewport', async ({ page }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/curated-cards&index=1&vtest=true',
      viewport: { width: 1024, height: 768 },
      screenshotName: 'curated-cards-1-Desktop.png',
    });
  });

  test('curated-cards (header-left) (1) visual test at Large viewport', async ({ page }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/curated-cards&index=1&vtest=true',
      viewport: { width: 1440, height: 900 },
      screenshotName: 'curated-cards-1-Large.png',
    });
  });
});
