// Generated by tools/visual-tests/generate-visual-tests.js -- do not edit by hand.
// Readiness/stubbing logic lives in tools/visual-tests/spec-helpers.js.
import { test } from '@playwright/test';
import runBlockVisualTest from '../../spec-helpers.js';

const BLOCK_SLUG = 'teaser';

test.describe('teaser Visual Tests', () => {
  test('teaser (light, left, cta1-primary, cta2-primary) visual test at Mobile viewport', async ({ page }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/teaser&index=0&vtest=true',
      viewport: { width: 320, height: 568 },
      screenshotName: 'teaser-0-Mobile.png',
    });
  });

  test('teaser (light, left, cta1-primary, cta2-primary) visual test at Tablet viewport', async ({ page }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/teaser&index=0&vtest=true',
      viewport: { width: 768, height: 1024 },
      screenshotName: 'teaser-0-Tablet.png',
    });
  });

  test('teaser (light, left, cta1-primary, cta2-primary) visual test at Desktop viewport', async ({ page }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/teaser&index=0&vtest=true',
      viewport: { width: 1024, height: 768 },
      screenshotName: 'teaser-0-Desktop.png',
    });
  });

  test('teaser (light, left, cta1-primary, cta2-primary) visual test at Large viewport', async ({ page }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/teaser&index=0&vtest=true',
      viewport: { width: 1440, height: 900 },
      screenshotName: 'teaser-0-Large.png',
    });
  });

  test('teaser (left, cta1-primary, cta2-primary, right) visual test at Mobile viewport', async ({ page }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/teaser&index=1&vtest=true',
      viewport: { width: 320, height: 568 },
      screenshotName: 'teaser-1-Mobile.png',
    });
  });

  test('teaser (left, cta1-primary, cta2-primary, right) visual test at Tablet viewport', async ({ page }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/teaser&index=1&vtest=true',
      viewport: { width: 768, height: 1024 },
      screenshotName: 'teaser-1-Tablet.png',
    });
  });

  test('teaser (left, cta1-primary, cta2-primary, right) visual test at Desktop viewport', async ({ page }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/teaser&index=1&vtest=true',
      viewport: { width: 1024, height: 768 },
      screenshotName: 'teaser-1-Desktop.png',
    });
  });

  test('teaser (left, cta1-primary, cta2-primary, right) visual test at Large viewport', async ({ page }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/teaser&index=1&vtest=true',
      viewport: { width: 1440, height: 900 },
      screenshotName: 'teaser-1-Large.png',
    });
  });

  test('teaser (left, bg-spectrum-gray-700, dark) visual test at Mobile viewport', async ({ page }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/teaser&index=2&vtest=true',
      viewport: { width: 320, height: 568 },
      screenshotName: 'teaser-2-Mobile.png',
    });
  });

  test('teaser (left, bg-spectrum-gray-700, dark) visual test at Tablet viewport', async ({ page }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/teaser&index=2&vtest=true',
      viewport: { width: 768, height: 1024 },
      screenshotName: 'teaser-2-Tablet.png',
    });
  });

  test('teaser (left, bg-spectrum-gray-700, dark) visual test at Desktop viewport', async ({ page }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/teaser&index=2&vtest=true',
      viewport: { width: 1024, height: 768 },
      screenshotName: 'teaser-2-Desktop.png',
    });
  });

  test('teaser (left, bg-spectrum-gray-700, dark) visual test at Large viewport', async ({ page }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/teaser&index=2&vtest=true',
      viewport: { width: 1440, height: 900 },
      screenshotName: 'teaser-2-Large.png',
    });
  });
});
