// Generated by tools/visual-tests/generate-visual-tests.js -- do not edit by hand.
// Readiness/stubbing logic lives in tools/visual-tests/spec-helpers.js.
import { test } from '@playwright/test';
import runBlockVisualTest from '../../spec-helpers.js';

const BLOCK_SLUG = 'columns';

test.describe('columns Visual Tests', () => {
  test('columns visual test at Mobile viewport', async ({ page }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/columns&index=0&vtest=true',
      viewport: { width: 320, height: 568 },
      screenshotName: 'columns-0-Mobile.png',
    });
  });

  test('columns visual test at Tablet viewport', async ({ page }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/columns&index=0&vtest=true',
      viewport: { width: 768, height: 1024 },
      screenshotName: 'columns-0-Tablet.png',
    });
  });

  test('columns visual test at Desktop viewport', async ({ page }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/columns&index=0&vtest=true',
      viewport: { width: 1024, height: 768 },
      screenshotName: 'columns-0-Desktop.png',
    });
  });

  test('columns visual test at Large viewport', async ({ page }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/columns&index=0&vtest=true',
      viewport: { width: 1440, height: 900 },
      screenshotName: 'columns-0-Large.png',
    });
  });

  test('columns (b-alt-row) visual test at Mobile viewport', async ({ page }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/columns&index=1&vtest=true',
      viewport: { width: 320, height: 568 },
      screenshotName: 'columns-1-Mobile.png',
    });
  });

  test('columns (b-alt-row) visual test at Tablet viewport', async ({ page }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/columns&index=1&vtest=true',
      viewport: { width: 768, height: 1024 },
      screenshotName: 'columns-1-Tablet.png',
    });
  });

  test('columns (b-alt-row) visual test at Desktop viewport', async ({ page }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/columns&index=1&vtest=true',
      viewport: { width: 1024, height: 768 },
      screenshotName: 'columns-1-Desktop.png',
    });
  });

  test('columns (b-alt-row) visual test at Large viewport', async ({ page }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/columns&index=1&vtest=true',
      viewport: { width: 1440, height: 900 },
      screenshotName: 'columns-1-Large.png',
    });
  });

  test('columns (align-middle) visual test at Mobile viewport', async ({ page }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/columns&index=2&vtest=true',
      viewport: { width: 320, height: 568 },
      screenshotName: 'columns-2-Mobile.png',
    });
  });

  test('columns (align-middle) visual test at Tablet viewport', async ({ page }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/columns&index=2&vtest=true',
      viewport: { width: 768, height: 1024 },
      screenshotName: 'columns-2-Tablet.png',
    });
  });

  test('columns (align-middle) visual test at Desktop viewport', async ({ page }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/columns&index=2&vtest=true',
      viewport: { width: 1024, height: 768 },
      screenshotName: 'columns-2-Desktop.png',
    });
  });

  test('columns (align-middle) visual test at Large viewport', async ({ page }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/columns&index=2&vtest=true',
      viewport: { width: 1440, height: 900 },
      screenshotName: 'columns-2-Large.png',
    });
  });
});
