// Generated by tools/visual-tests/generate-visual-tests.js -- do not edit by hand.
// Readiness/stubbing logic lives in tools/visual-tests/spec-helpers.js.
import { test } from '@playwright/test';
import runBlockVisualTest from '../../spec-helpers.js';

const BLOCK_SLUG = 'block-quote';

test.describe('block-quote Visual Tests', () => {
  test('block-quote (adobe) visual test at Mobile viewport', async ({ page }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/block-quote&index=0&vtest=true',
      viewport: { width: 320, height: 568 },
      screenshotName: 'block-quote-0-Mobile.png',
    });
  });

  test('block-quote (adobe) visual test at Tablet viewport', async ({ page }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/block-quote&index=0&vtest=true',
      viewport: { width: 768, height: 1024 },
      screenshotName: 'block-quote-0-Tablet.png',
    });
  });

  test('block-quote (adobe) visual test at Desktop viewport', async ({ page }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/block-quote&index=0&vtest=true',
      viewport: { width: 1024, height: 768 },
      screenshotName: 'block-quote-0-Desktop.png',
    });
  });

  test('block-quote (adobe) visual test at Large viewport', async ({ page }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/block-quote&index=0&vtest=true',
      viewport: { width: 1440, height: 900 },
      screenshotName: 'block-quote-0-Large.png',
    });
  });

  test('block-quote (external) visual test at Mobile viewport', async ({ page }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/block-quote&index=1&vtest=true',
      viewport: { width: 320, height: 568 },
      screenshotName: 'block-quote-1-Mobile.png',
    });
  });

  test('block-quote (external) visual test at Tablet viewport', async ({ page }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/block-quote&index=1&vtest=true',
      viewport: { width: 768, height: 1024 },
      screenshotName: 'block-quote-1-Tablet.png',
    });
  });

  test('block-quote (external) visual test at Desktop viewport', async ({ page }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/block-quote&index=1&vtest=true',
      viewport: { width: 1024, height: 768 },
      screenshotName: 'block-quote-1-Desktop.png',
    });
  });

  test('block-quote (external) visual test at Large viewport', async ({ page }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/block-quote&index=1&vtest=true',
      viewport: { width: 1440, height: 900 },
      screenshotName: 'block-quote-1-Large.png',
    });
  });
});
