// Generated by tools/visual-tests/generate-visual-tests.js -- do not edit by hand.
// Readiness/stubbing logic lives in tools/visual-tests/spec-helpers.js.
import { test } from '@playwright/test';
import runBlockVisualTest from '../../spec-helpers.js';

const BLOCK_SLUG = 'announcement-ribbon';

test.describe('announcement-ribbon Visual Tests', () => {
  test('announcement-ribbon (light, cta1-primary, cta2-primary) visual test at Mobile viewport', async ({ page }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/announcement-ribbon&index=0&vtest=true',
      viewport: { width: 320, height: 568 },
      screenshotName: 'announcement-ribbon-0-Mobile.png',
    });
  });

  test('announcement-ribbon (light, cta1-primary, cta2-primary) visual test at Tablet viewport', async ({ page }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/announcement-ribbon&index=0&vtest=true',
      viewport: { width: 768, height: 1024 },
      screenshotName: 'announcement-ribbon-0-Tablet.png',
    });
  });

  test('announcement-ribbon (light, cta1-primary, cta2-primary) visual test at Desktop viewport', async ({ page }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/announcement-ribbon&index=0&vtest=true',
      viewport: { width: 1024, height: 768 },
      screenshotName: 'announcement-ribbon-0-Desktop.png',
    });
  });

  test('announcement-ribbon (light, cta1-primary, cta2-primary) visual test at Large viewport', async ({ page }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/announcement-ribbon&index=0&vtest=true',
      viewport: { width: 1440, height: 900 },
      screenshotName: 'announcement-ribbon-0-Large.png',
    });
  });

  test('announcement-ribbon (cta1-primary, cta2-primary, dark, bg-non-spectrum-adobe-red) visual test at Mobile viewport', async ({
    page,
  }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/announcement-ribbon&index=1&vtest=true',
      viewport: { width: 320, height: 568 },
      screenshotName: 'announcement-ribbon-1-Mobile.png',
    });
  });

  test('announcement-ribbon (cta1-primary, cta2-primary, dark, bg-non-spectrum-adobe-red) visual test at Tablet viewport', async ({
    page,
  }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/announcement-ribbon&index=1&vtest=true',
      viewport: { width: 768, height: 1024 },
      screenshotName: 'announcement-ribbon-1-Tablet.png',
    });
  });

  test('announcement-ribbon (cta1-primary, cta2-primary, dark, bg-non-spectrum-adobe-red) visual test at Desktop viewport', async ({
    page,
  }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/announcement-ribbon&index=1&vtest=true',
      viewport: { width: 1024, height: 768 },
      screenshotName: 'announcement-ribbon-1-Desktop.png',
    });
  });

  test('announcement-ribbon (cta1-primary, cta2-primary, dark, bg-non-spectrum-adobe-red) visual test at Large viewport', async ({
    page,
  }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/announcement-ribbon&index=1&vtest=true',
      viewport: { width: 1440, height: 900 },
      screenshotName: 'announcement-ribbon-1-Large.png',
    });
  });
});
