// Generated by tools/visual-tests/generate-visual-tests.js -- do not edit by hand.
// Readiness/stubbing logic lives in tools/visual-tests/spec-helpers.js.
import { test } from '@playwright/test';
import runBlockVisualTest from '../../spec-helpers.js';

const BLOCK_SLUG = 'marquee';

test.describe('marquee Visual Tests', () => {
  test('marquee (straight, bg-spectrum-blue-700, large) visual test at Mobile viewport', async ({ page }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/marquee&index=0&vtest=true',
      viewport: { width: 320, height: 568 },
      screenshotName: 'marquee-0-Mobile.png',
    });
  });

  test('marquee (straight, bg-spectrum-blue-700, large) visual test at Tablet viewport', async ({ page }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/marquee&index=0&vtest=true',
      viewport: { width: 768, height: 1024 },
      screenshotName: 'marquee-0-Tablet.png',
    });
  });

  test('marquee (straight, bg-spectrum-blue-700, large) visual test at Desktop viewport', async ({ page }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/marquee&index=0&vtest=true',
      viewport: { width: 1024, height: 768 },
      screenshotName: 'marquee-0-Desktop.png',
    });
  });

  test('marquee (straight, bg-spectrum-blue-700, large) visual test at Large viewport', async ({ page }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/marquee&index=0&vtest=true',
      viewport: { width: 1440, height: 900 },
      screenshotName: 'marquee-0-Large.png',
    });
  });

  test('marquee (medium, curved, text-spectrum-gray-900, bg-spectrum-red-700) visual test at Mobile viewport', async ({
    page,
  }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/marquee&index=1&vtest=true',
      viewport: { width: 320, height: 568 },
      screenshotName: 'marquee-1-Mobile.png',
    });
  });

  test('marquee (medium, curved, text-spectrum-gray-900, bg-spectrum-red-700) visual test at Tablet viewport', async ({
    page,
  }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/marquee&index=1&vtest=true',
      viewport: { width: 768, height: 1024 },
      screenshotName: 'marquee-1-Tablet.png',
    });
  });

  test('marquee (medium, curved, text-spectrum-gray-900, bg-spectrum-red-700) visual test at Desktop viewport', async ({
    page,
  }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/marquee&index=1&vtest=true',
      viewport: { width: 1024, height: 768 },
      screenshotName: 'marquee-1-Desktop.png',
    });
  });

  test('marquee (medium, curved, text-spectrum-gray-900, bg-spectrum-red-700) visual test at Large viewport', async ({
    page,
  }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/marquee&index=1&vtest=true',
      viewport: { width: 1440, height: 900 },
      screenshotName: 'marquee-1-Large.png',
    });
  });

  test('marquee (text-spectrum-gray-900, small, straight, bg-spectrum-yellow-700) visual test at Mobile viewport', async ({
    page,
  }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/marquee&index=2&vtest=true',
      viewport: { width: 320, height: 568 },
      screenshotName: 'marquee-2-Mobile.png',
    });
  });

  test('marquee (text-spectrum-gray-900, small, straight, bg-spectrum-yellow-700) visual test at Tablet viewport', async ({
    page,
  }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/marquee&index=2&vtest=true',
      viewport: { width: 768, height: 1024 },
      screenshotName: 'marquee-2-Tablet.png',
    });
  });

  test('marquee (text-spectrum-gray-900, small, straight, bg-spectrum-yellow-700) visual test at Desktop viewport', async ({
    page,
  }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/marquee&index=2&vtest=true',
      viewport: { width: 1024, height: 768 },
      screenshotName: 'marquee-2-Desktop.png',
    });
  });

  test('marquee (text-spectrum-gray-900, small, straight, bg-spectrum-yellow-700) visual test at Large viewport', async ({
    page,
  }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/marquee&index=2&vtest=true',
      viewport: { width: 1440, height: 900 },
      screenshotName: 'marquee-2-Large.png',
    });
  });

  test('marquee (medium, text-spectrum-gray-900, straight, fill-background, bg-spectrum-celery-700) visual test at Mobile viewport', async ({
    page,
  }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/marquee&index=3&vtest=true',
      viewport: { width: 320, height: 568 },
      screenshotName: 'marquee-3-Mobile.png',
    });
  });

  test('marquee (medium, text-spectrum-gray-900, straight, fill-background, bg-spectrum-celery-700) visual test at Tablet viewport', async ({
    page,
  }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/marquee&index=3&vtest=true',
      viewport: { width: 768, height: 1024 },
      screenshotName: 'marquee-3-Tablet.png',
    });
  });

  test('marquee (medium, text-spectrum-gray-900, straight, fill-background, bg-spectrum-celery-700) visual test at Desktop viewport', async ({
    page,
  }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/marquee&index=3&vtest=true',
      viewport: { width: 1024, height: 768 },
      screenshotName: 'marquee-3-Desktop.png',
    });
  });

  test('marquee (medium, text-spectrum-gray-900, straight, fill-background, bg-spectrum-celery-700) visual test at Large viewport', async ({
    page,
  }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/marquee&index=3&vtest=true',
      viewport: { width: 1440, height: 900 },
      screenshotName: 'marquee-3-Large.png',
    });
  });

  test('marquee (bg-spectrum-gray-700, large, straight, fill-background, text-spectrum-gray-50) visual test at Mobile viewport', async ({
    page,
  }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/marquee&index=4&vtest=true',
      viewport: { width: 320, height: 568 },
      screenshotName: 'marquee-4-Mobile.png',
    });
  });

  test('marquee (bg-spectrum-gray-700, large, straight, fill-background, text-spectrum-gray-50) visual test at Tablet viewport', async ({
    page,
  }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/marquee&index=4&vtest=true',
      viewport: { width: 768, height: 1024 },
      screenshotName: 'marquee-4-Tablet.png',
    });
  });

  test('marquee (bg-spectrum-gray-700, large, straight, fill-background, text-spectrum-gray-50) visual test at Desktop viewport', async ({
    page,
  }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/marquee&index=4&vtest=true',
      viewport: { width: 1024, height: 768 },
      screenshotName: 'marquee-4-Desktop.png',
    });
  });

  test('marquee (bg-spectrum-gray-700, large, straight, fill-background, text-spectrum-gray-50) visual test at Large viewport', async ({
    page,
  }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/marquee&index=4&vtest=true',
      viewport: { width: 1440, height: 900 },
      screenshotName: 'marquee-4-Large.png',
    });
  });

  test('marquee (medium, straight, bg-spectrum-fuchsia-700, text-spectrum-gray-900) visual test at Mobile viewport', async ({
    page,
  }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/marquee&index=5&vtest=true',
      viewport: { width: 320, height: 568 },
      screenshotName: 'marquee-5-Mobile.png',
    });
  });

  test('marquee (medium, straight, bg-spectrum-fuchsia-700, text-spectrum-gray-900) visual test at Tablet viewport', async ({
    page,
  }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/marquee&index=5&vtest=true',
      viewport: { width: 768, height: 1024 },
      screenshotName: 'marquee-5-Tablet.png',
    });
  });

  test('marquee (medium, straight, bg-spectrum-fuchsia-700, text-spectrum-gray-900) visual test at Desktop viewport', async ({
    page,
  }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/marquee&index=5&vtest=true',
      viewport: { width: 1024, height: 768 },
      screenshotName: 'marquee-5-Desktop.png',
    });
  });

  test('marquee (medium, straight, bg-spectrum-fuchsia-700, text-spectrum-gray-900) visual test at Large viewport', async ({
    page,
  }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/marquee&index=5&vtest=true',
      viewport: { width: 1440, height: 900 },
      screenshotName: 'marquee-5-Large.png',
    });
  });
});
