// Generated by tools/visual-tests/generate-visual-tests.js -- do not edit by hand.
// Readiness/stubbing logic lives in tools/visual-tests/spec-helpers.js.
import { test } from '@playwright/test';
import runBlockVisualTest from '../../spec-helpers.js';

const BLOCK_SLUG = 'media-panel';

test.describe('media-panel Visual Tests', () => {
  test('media-panel (left, cta-secondary) visual test at Mobile viewport', async ({ page }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/media-panel&index=0&vtest=true',
      viewport: { width: 320, height: 568 },
      screenshotName: 'media-panel-0-Mobile.png',
    });
  });

  test('media-panel (left, cta-secondary) visual test at Tablet viewport', async ({ page }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/media-panel&index=0&vtest=true',
      viewport: { width: 768, height: 1024 },
      screenshotName: 'media-panel-0-Tablet.png',
    });
  });

  test('media-panel (left, cta-secondary) visual test at Desktop viewport', async ({ page }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/media-panel&index=0&vtest=true',
      viewport: { width: 1024, height: 768 },
      screenshotName: 'media-panel-0-Desktop.png',
    });
  });

  test('media-panel (left, cta-secondary) visual test at Large viewport', async ({ page }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/media-panel&index=0&vtest=true',
      viewport: { width: 1440, height: 900 },
      screenshotName: 'media-panel-0-Large.png',
    });
  });

  test('media-panel (cta-secondary, right) visual test at Mobile viewport', async ({ page }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/media-panel&index=1&vtest=true',
      viewport: { width: 320, height: 568 },
      screenshotName: 'media-panel-1-Mobile.png',
    });
  });

  test('media-panel (cta-secondary, right) visual test at Tablet viewport', async ({ page }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/media-panel&index=1&vtest=true',
      viewport: { width: 768, height: 1024 },
      screenshotName: 'media-panel-1-Tablet.png',
    });
  });

  test('media-panel (cta-secondary, right) visual test at Desktop viewport', async ({ page }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/media-panel&index=1&vtest=true',
      viewport: { width: 1024, height: 768 },
      screenshotName: 'media-panel-1-Desktop.png',
    });
  });

  test('media-panel (cta-secondary, right) visual test at Large viewport', async ({ page }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/media-panel&index=1&vtest=true',
      viewport: { width: 1440, height: 900 },
      screenshotName: 'media-panel-1-Large.png',
    });
  });

  test('media-panel (podcast-card, cta-tertiary) visual test at Mobile viewport', async ({ page }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/media-panel&index=2&vtest=true',
      viewport: { width: 320, height: 568 },
      screenshotName: 'media-panel-2-Mobile.png',
    });
  });

  test('media-panel (podcast-card, cta-tertiary) visual test at Tablet viewport', async ({ page }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/media-panel&index=2&vtest=true',
      viewport: { width: 768, height: 1024 },
      screenshotName: 'media-panel-2-Tablet.png',
    });
  });

  test('media-panel (podcast-card, cta-tertiary) visual test at Desktop viewport', async ({ page }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/media-panel&index=2&vtest=true',
      viewport: { width: 1024, height: 768 },
      screenshotName: 'media-panel-2-Desktop.png',
    });
  });

  test('media-panel (podcast-card, cta-tertiary) visual test at Large viewport', async ({ page }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/media-panel&index=2&vtest=true',
      viewport: { width: 1440, height: 900 },
      screenshotName: 'media-panel-2-Large.png',
    });
  });
});
