// Generated by tools/visual-tests/generate-visual-tests.js -- do not edit by hand.
// Readiness/stubbing logic lives in tools/visual-tests/spec-helpers.js.
import { test } from '@playwright/test';
import runBlockVisualTest from '../../spec-helpers.js';

const BLOCK_SLUG = 'carousel';

test.describe('carousel Visual Tests', () => {
  test('carousel (0) visual test at Mobile viewport', async ({ page }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/carousel&index=0&vtest=true',
      viewport: { width: 320, height: 568 },
      screenshotName: 'carousel-0-Mobile.png',
    });
  });

  test('carousel (0) visual test at Tablet viewport', async ({ page }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/carousel&index=0&vtest=true',
      viewport: { width: 768, height: 1024 },
      screenshotName: 'carousel-0-Tablet.png',
    });
  });

  test('carousel (0) visual test at Desktop viewport', async ({ page }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/carousel&index=0&vtest=true',
      viewport: { width: 1024, height: 768 },
      screenshotName: 'carousel-0-Desktop.png',
    });
  });

  test('carousel (0) visual test at Large viewport', async ({ page }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/carousel&index=0&vtest=true',
      viewport: { width: 1440, height: 900 },
      screenshotName: 'carousel-0-Large.png',
    });
  });

  test('carousel (1) visual test at Mobile viewport', async ({ page }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/carousel&index=1&vtest=true',
      viewport: { width: 320, height: 568 },
      screenshotName: 'carousel-1-Mobile.png',
    });
  });

  test('carousel (1) visual test at Tablet viewport', async ({ page }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/carousel&index=1&vtest=true',
      viewport: { width: 768, height: 1024 },
      screenshotName: 'carousel-1-Tablet.png',
    });
  });

  test('carousel (1) visual test at Desktop viewport', async ({ page }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/carousel&index=1&vtest=true',
      viewport: { width: 1024, height: 768 },
      screenshotName: 'carousel-1-Desktop.png',
    });
  });

  test('carousel (1) visual test at Large viewport', async ({ page }) => {
    await runBlockVisualTest(page, {
      blockSlug: BLOCK_SLUG,
      url: '/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/carousel&index=1&vtest=true',
      viewport: { width: 1440, height: 900 },
      screenshotName: 'carousel-1-Large.png',
    });
  });
});
