name: Page Publish

on:
  repository_dispatch:
    types:
      - resource-published

jobs:
  build-coveo:
    runs-on: ubuntu-latest
    if: contains(github.event.client_payload.path, '/articles/') && !contains(github.event.client_payload.path, '/articles/authors')
    steps:
      - name: Extract language
        id: get_language
        run: |
          path="${{ github.event.client_payload.path }}"
          echo "Path: $path"  # Debugging statement
          language=$(echo "$path" | awk -F '/' '{print $2}')
          echo "Language extracted: $language"  # Debugging statement
          echo "::set-output name=language::$language"

      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install JSDOM
        id: install_jsdom
        run: |
          if [ ! -d "${{ runner.workspace }}/node_modules/jsdom" ]; then
            npm install jsdom
          fi

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - name: Get Repository Details
        id: get_repo_details
        run: |
          repo_name=$(echo "${{ github.repository }}" | cut -d'/' -f2)
          echo "::set-output name=repo_name::$repo_name"

      - name: Generate Coveo Index
        working-directory: ./coveo
        run: |
          node generate-coveo-index.js \
            --language ${{ steps.get_language.outputs.language }} \
            --repo-name ${{ steps.get_repo_details.outputs.repo_name }} \
            > coveo_${{ steps.get_language.outputs.language }}.xml

          # Check if the file exists or has been modified
          if [ -f ./coveo_${{ steps.get_language.outputs.language }}.xml ]; then
            echo "File exists"
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add ./coveo_articles_${{ steps.get_language.outputs.language }}.xml
            git commit -m "Update generated coveo_${{ steps.get_language.outputs.language }}.xml file"
            git push
          else
            echo "File does not exist"
            exit 1
          fi
